import cv2
image = cv2.imread(r"C:\Users\prasa.SIVA_REDDY\OneDrive\Pictures\WhatsApp Image kung fu.jpg") 
cv2.imshow('Original', image)
cv2.waitKey(0)
gaussian = cv2.GaussianBlur(image, (5, 5), 0)
cv2.imshow('Gaussian Blur', gaussian)
cv2.waitKey(0)
median = cv2.medianBlur(image, 5)
cv2.imshow('Median Blur', median)
cv2.waitKey(0)
bilateral = cv2.bilateralFilter(image, d=9, sigmaColor=75, sigmaSpace=75)
cv2.imshow('Bilateral Filter', bilateral)
cv2.waitKey(0)
cv2.destroyAllWindows()
